`timescale 1 ns / 1 ps

// Testbench
`define FISMOS_TB_TRIGGER_INTERRUPT_TO_FISMOS
// `define FISMOS_DEBUG_STATIC_INTERRUPT_TO_LINUX
`define FISMOS_DEBUG_PRELOAD_INPUTMEMORY
`define FISMOS_TB_DEBUG

`define FISMOS_TB_CHECK_AES_DECRYPT 32'hdf00_0001
`define FISMOS_TB_CHECK_HMAC_COMPUTE_ON_INPUT_DATA 32'hdf00_0003
`define FISMOS_TB_CHECK_HMAC_COMPARE_ON_INPUT_DATA 32'hdf00_0004
`define FISMOS_TB_CHECK_RSA_SIGN_ON_INPUT_DATA 32'hdf00_0005
`define FISMOS_TB_CHECK_KEYSTORAGE 32'hdf00_000f
`define FISMOS_TB_ACTIVE_CHECK_MODE `FISMOS_TB_CHECK_AES_DECRYPT

// FISMOS
// `define FISMOS_SPLIT_AXI_CLK_INPUT 
`define RESET_ONESHOT
`define AXI_SLAVE_INTERFACE_ACTIVATE
`define OUTLINE_INTERRUPT_TO_LINUX

// Memory
`define FISMOS_SET_CPU_MEM_SIZE_KBYTE 256
`define FISMOS_OUT32BIT_ADDRESS 32'h1000_0000
`define FISMOS_CONTROL_REGISTER_ADDRESS 32'hff00_0000
`define FISMOS_STATUS_REGISTER_ADDRESS 32'hff00_0004
`define FISMOS_EXCHANGE_BUFFER_BASE_ADDRESS 32'hff00_0008
`define FISMOS_STACK_ADDRESS 32'hffff_ffff

// PicoRV32
`define FISMOS_ENABLE_INTERRUPT 0
`define FISMOS_MASKED_IRQ 32'hffff_ffff
`define FISMOS_LATCHED_IRQ 32'h0000_0000

// Shared Memory
// `define FISMOS_STATIC_INTERRUPT_TO_PICORV32
`define FISMOS_SET_AXI_ADDR_WIDTH 7
`define FISMOS_SET_AXI_DATA_WIDTH 32

`define FISMOS_CONTROL_REGISTER_OFFSET 32'h0000_0000
`define FISMOS_STATUS_REGISTER_OFFSET 32'h0000_0004
`define FISMOS_EXCHANGE_BUFFER_OFFSET 32'h0000_0008
